import Header from '@components/Header'
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const StarBackground = dynamic(() => import('@components/StarBackground'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CODER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <StarBackground />
        {/* <FloatText /> */}
      </main>
    </div>
  )
}

export default Home
